require 'switchboard/jacks/auto_accept'
require 'switchboard/jacks/debug'
require 'switchboard/jacks/echo'
require 'switchboard/jacks/muc'
require 'switchboard/jacks/notify'
require 'switchboard/jacks/oauth_pubsub'
require 'switchboard/jacks/pubsub'
require 'switchboard/jacks/roster_debug'
