require 'switchboard/commands/roster/roster'
require 'switchboard/commands/roster/add'
require 'switchboard/commands/roster/list'
require 'switchboard/commands/roster/online'
require 'switchboard/commands/roster/remove'
